version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PruebaHola1!
      - MSSQL_PID=Developer
    ports:
      - "1400:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "PruebaHola1!", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:10-alpine
    container_name: flyway_migrations
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./flyway/sql:/flyway/sql
    command: [
      "-url=jdbc:sqlserver://sqlserver:1400;databaseName=master;encrypt=true;trustServerCertificate=true",
      "-user=sa",
      "-password=PruebaHola1!",
      "migrate"
    ]
  
  # Node.js backend application service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000" # Maps port 3000 on your machine to port 3000 in the container
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app         # Live code reloading: mounts host files to container
      - /usr/src/app/node_modules # Prevents host files from overriding container node_modules
      
volumes:
  sqlserver_data:
