/*
    Gathel - V2__insert_catalogs.sql
    Database engine: SQL Server
    Database name: Gathel

    Flyway versioned migration.

    Purpose:
    - Inserts the initial catalog values required by the Gathel database.
    - Populates lookup tables and type tables used by the physical schema.
    - Provides base values required before inserting users, wallets, propositions, payments or predictions.
*/

DECLARE @now DATETIME2 = SYSDATETIME();
DECLARE @checksum VARBINARY(32) = CONVERT(VARBINARY(32), HASHBYTES('SHA2_256', 'GATHEL_CATALOG_SEED'));

/* LOG CATALOGS */
INSERT INTO logTypes (code, description, enabled) VALUES
('USER', 'Events generated by users', 1),
('AI', 'Events generated by artificial intelligence processes', 1),
('SYSTEM', 'Internal system events', 1),
('SECURITY', 'Security and authorization events', 1),
('PAYMENT', 'Payment related events', 1);

INSERT INTO eventTypes (code, description, enabled) VALUES
('LOGIN', 'User login', 1),
('LOGOUT', 'User logout', 1),
('INSERT', 'Insert operation', 1),
('UPDATE', 'Update operation', 1),
('DELETE', 'Delete operation', 1),
('PAYMENT_ATTEMPT', 'Payment attempt registered', 1),
('AI_REVIEW', 'AI review executed', 1),
('TRANSACTION_CREATED', 'Wallet transaction created', 1),
('PROPOSITION_CREATED', 'Proposition created', 1),
('PREDICTION_CREATED', 'Prediction created', 1);

INSERT INTO severities (code, level, enabled) VALUES
('INFO', '1', 1),
('WARNING', '2', 1),
('ERROR', '3', 1),
('CRITICAL', '4', 1);

INSERT INTO sources (code, description, enabled) VALUES
('FRONTEND', 'Web or mobile frontend', 1),
('BACKEND', 'REST API backend', 1),
('DATABASE', 'SQL Server database', 1),
('AI_PROVIDER', 'Artificial intelligence provider', 1),
('PAYMENT_PROVIDER', 'External payment provider', 1),
('SOCIAL_MEDIA', 'Social media platform', 1),
('FLYWAY', 'Flyway migration process', 1);

INSERT INTO dataObjects (code, description, enabled) VALUES
('USERS', 'Users table', 1),
('PROPOSITIONS', 'Propositions table', 1),
('PREDICTIONS', 'Predictions table', 1),
('PAYMENT_ATTEMPTS', 'Payment attempts table', 1),
('TRANSACTIONS', 'Transactions table', 1),
('AI_PROCESS_LOGS', 'AI process logs table', 1),
('SOCIAL_MEDIA_POSTS', 'Social media posts table', 1),
('WALLETS', 'Wallets table', 1);

/* USERS / ROLES */
INSERT INTO roleTypes (code, description, enabled) VALUES
('ADMIN', 'Database and platform administrator', 1),
('PLAYER', 'Regular Gathel player', 1),
('BUSINESS', 'Affiliated business user', 1),
('SUPPORT', 'Support operator', 1),
('READONLY', 'Read only user for reporting', 1);

/* CURRENCIES */
INSERT INTO currencyTypes (code, description, enabled) VALUES
('FIAT', 'Real world currency', 1),
('VIRTUAL', 'Virtual platform currency', 1);

INSERT INTO currencies (currencyTypeId, code, name, symbol, countryId, enabled, createdAt, updatedAt, checksum)
VALUES
((SELECT id FROM currencyTypes WHERE code = 'FIAT'), 'USD', 'US Dollar', '$', NULL, 1, @now, NULL, @checksum),
((SELECT id FROM currencyTypes WHERE code = 'FIAT'), 'CRC', 'Costa Rican Colon', '₡', NULL, 1, @now, NULL, @checksum),
((SELECT id FROM currencyTypes WHERE code = 'FIAT'), 'EUR', 'Euro', '€', NULL, 1, @now, NULL, @checksum),
((SELECT id FROM currencyTypes WHERE code = 'VIRTUAL'), 'PTS', 'Gathel Points', 'pts', NULL, 1, @now, NULL, @checksum);

/* TAXES */
INSERT INTO taxTypes (code, name, description, enabled) VALUES
('VAT', 'Value Added Tax', 'General value added tax', 1),
('SALES_TAX', 'Sales Tax', 'Sales tax by country or state', 1),
('WITHDRAWAL_TAX', 'Withdrawal Tax', 'Tax applied to money withdrawals', 1),
('SERVICE_FEE', 'Service Fee', 'Platform or provider service fee', 1);

/* SOCIAL MEDIA */
INSERT INTO socialMedia (code, name, enabled) VALUES
('INSTAGRAM', 'Instagram', 1),
('TIKTOK', 'TikTok', 1),
('X', 'X', 1),
('FACEBOOK', 'Facebook', 1),
('YOUTUBE', 'YouTube', 1);

INSERT INTO socialMediaPostsTypes (code, description, enabled) VALUES
('POST', 'Regular social media post', 1),
('STORY', 'Temporary story', 1),
('REEL', 'Short vertical video', 1),
('VIDEO', 'Video publication', 1),
('COMMENT', 'Comment on a publication', 1);

INSERT INTO propositionSourcePostUse (code, description, enabled) VALUES
('ORIGIN', 'Post that originated or inspired a proposition', 1),
('EVIDENCE', 'Post used as evidence during the process', 1),
('RESULT_VALIDATION', 'Post used to validate the final result', 1);

/* AI */
INSERT INTO aiProviders (code, name, enabled) VALUES
('OPENAI', 'OpenAI', 1),
('GEMINI', 'Google Gemini', 1),
('CLAUDE', 'Anthropic Claude', 1),
('LOCAL_MODEL', 'Local Model', 1);

INSERT INTO aiModels (aiProviderId, modelName, version, enabled) VALUES
((SELECT id FROM aiProviders WHERE code = 'OPENAI'), 'gpt-model-placeholder', '1', 1),
((SELECT id FROM aiProviders WHERE code = 'GEMINI'), 'gemini-model-placeholder', '1', 1),
((SELECT id FROM aiProviders WHERE code = 'CLAUDE'), 'claude-model-placeholder', '1', 1),
((SELECT id FROM aiProviders WHERE code = 'LOCAL_MODEL'), 'local-safety-model', '1', 1);

INSERT INTO aiProcessTypes (code, description, enabled) VALUES
('PROPOSITION_CREATION_REVIEW', 'AI review applied when a proposition is created', 1),
('ETHICAL_REVIEW', 'AI review for ethical, legal and safety rules', 1),
('RESULT_VALIDATION', 'AI review for validating proposition result evidence', 1),
('FRAUD_REVIEW', 'AI review for detecting fraud or manipulation', 1);

INSERT INTO aiResults (code, description, enabled) VALUES
('APPROVED', 'AI approved the analyzed object', 1),
('REJECTED', 'AI rejected the analyzed object', 1),
('INCONCLUSIVE', 'AI could not determine a final result', 1),
('NEEDS_MORE_EVIDENCE', 'AI requires additional evidence', 1),
('ERROR', 'AI process failed', 1);

/* SETTINGS */
INSERT INTO settingsTypes (code, description, enabled) VALUES
('INITIAL_PLAYER_POINTS', 'Initial points assigned to a player', 1),
('REJECT_PENALTY_POINTS', 'Points penalty when selected proposition is rejected', 1),
('UNVERIFIABLE_PENALTY_PERCENTAGE', 'Penalty percentage when result cannot be verified', 1),
('PROPOSER_EARNINGS_PERCENTAGE', 'Earnings percentage assigned to proposition target', 1),
('PLATFORM_EARNINGS_PERCENTAGE', 'Earnings percentage assigned to Gathel platform', 1),
('MAX_POINTS_PER_PREDICTION', 'Maximum points allowed per prediction', 1);

INSERT INTO settings (settingTypeId, settingValue, valueType, description, enabled, updatedBy, updatedAt) VALUES
((SELECT id FROM settingsTypes WHERE code = 'INITIAL_PLAYER_POINTS'), '100', 'INT', 'Each player starts with 100 Gathel points', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'REJECT_PENALTY_POINTS'), '1', 'INT', 'A player loses 1 point when rejecting the selected proposition', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'UNVERIFIABLE_PENALTY_PERCENTAGE'), '15', 'DECIMAL', 'A player loses 15 percent if result cannot be verified', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'PROPOSER_EARNINGS_PERCENTAGE'), '5', 'DECIMAL', 'Percentage assigned to the person executing the proposition', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'PLATFORM_EARNINGS_PERCENTAGE'), '5', 'DECIMAL', 'Percentage assigned to the platform', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'MAX_POINTS_PER_PREDICTION'), '1', 'INT', 'Maximum points allowed per prediction', 1, NULL, @now);

/* PAYMENTS */
INSERT INTO paymentTypes (code, description, enabled) VALUES
('CARD', 'Card payment through external processor', 1),
('SINPE', 'SINPE transfer through external provider', 1),
('PAYPAL', 'PayPal payment', 1),
('BANK_TRANSFER', 'Bank transfer', 1),
('INTERNAL_BALANCE', 'Internal wallet balance movement', 1);

INSERT INTO paymentProviders (code, name, baseUrl, enabled, createdAt, updatedAt) VALUES
('PAYPAL_API', 'PayPal API', 'https://api-m.sandbox.paypal.com', 1, @now, NULL),
('SINPE_API', 'SINPE API', 'https://sandbox.sinpe.example/api', 1, @now, NULL),
('CARD_PROCESSOR', 'Card Processor Sandbox', 'https://sandbox.cardprocessor.example/api', 1, @now, NULL),
('INTERNAL_ENGINE', 'Gathel Internal Balance Engine', NULL, 1, @now, NULL);

INSERT INTO operationTypes (code, description, enabled) VALUES
('POINTS_PURCHASE', 'Purchase virtual points', 1),
('MONEY_DEPOSIT', 'Deposit real money into wallet', 1),
('MONEY_WITHDRAWAL', 'Withdraw real money from wallet', 1),
('PREDICTION_BET', 'Bet points or money on a prediction', 1),
('REWARD_PAYMENT', 'Payment of rewards to winners', 1),
('COMMISSION_PAYMENT', 'Commission payment to platform or proposition target', 1),
('PENALTY', 'Penalty applied to a player', 1);

INSERT INTO paymentStatuses (code, description, enabled) VALUES
('PENDING', 'Payment attempt is pending', 1),
('APPROVED', 'Payment attempt was approved', 1),
('REJECTED', 'Payment attempt was rejected', 1),
('ERROR', 'Payment attempt ended with error', 1),
('CANCELLED', 'Payment attempt was cancelled', 1),
('INSUFFICIENT_FUNDS', 'Payment attempt failed due to insufficient funds', 1);

INSERT INTO paymentValidationTypes (code, description, enabled) VALUES
('METHOD_CHECK', 'Payment method validation', 1),
('COUNTRY_CHECK', 'Country validation', 1),
('FUNDS_CHECK', 'Funds validation', 1),
('PROVIDER_RESPONSE', 'External provider response validation', 1),
('FRAUD_CHECK', 'Fraud validation', 1);

INSERT INTO paymentValidationStatuses (code, description, enabled) VALUES
('PENDING', 'Validation is pending', 1),
('APPROVED', 'Validation was approved', 1),
('REJECTED', 'Validation was rejected', 1),
('ERROR', 'Validation ended with error', 1);

/* TRANSACTIONS */
INSERT INTO transactionTypes (code, description, createdAt, createdBy, enabled) VALUES
('BALANCE_IN', 'Balance increase', @now, NULL, 1),
('BALANCE_OUT', 'Balance decrease', @now, NULL, 1),
('BET', 'Prediction bet', @now, NULL, 1),
('REWARD', 'Reward payment', @now, NULL, 1),
('COMMISSION', 'Commission payment', @now, NULL, 1),
('PENALTY', 'Penalty transaction', @now, NULL, 1),
('REDEMPTION', 'Redeemable product redemption', @now, NULL, 1);

/* BUSINESS / PRODUCTS */
INSERT INTO quantityTypes (code, description, enabled) VALUES
('UNIT', 'Single unit', 1),
('BOTTLE', 'Bottle', 1),
('PAIR', 'Pair', 1),
('PACKAGE', 'Package', 1);

INSERT INTO unitMeasurements (code, description, enabled) VALUES
('CM', 'Centimeter', 1),
('ML', 'Milliliter', 1),
('KG', 'Kilogram', 1),
('UNIT', 'Unit', 1);

INSERT INTO productCharacteristics (name, enabled) VALUES
('Color', 1),
('Material', 1),
('Size', 1),
('Capacity', 1),
('Brand', 1);

INSERT INTO redemptionStatuses (status, description, enabled) VALUES
('PENDING', 'Redemption is pending', 1),
('APPROVED', 'Redemption was approved', 1),
('REJECTED', 'Redemption was rejected', 1),
('DELIVERED', 'Product was delivered', 1),
('CANCELLED', 'Redemption was cancelled', 1);

/* PROPOSITIONS / PREDICTIONS */
INSERT INTO propositionStatuses (code, description, enabled) VALUES
('PROPOSED', 'Proposition was created', 1),
('UNDER_AI_REVIEW', 'Proposition is under AI review', 1),
('VOTING', 'Proposition is available for votes', 1),
('SELECTED', 'Proposition was selected after voting', 1),
('ACCEPTED', 'Proposition was accepted by target player', 1),
('REJECTED', 'Proposition was rejected by target player', 1),
('ACTIVE', 'Proposition is active for predictions', 1),
('COMPLETED', 'Proposition was completed', 1),
('CANCELLED', 'Proposition was cancelled', 1),
('UNVERIFIABLE', 'Proposition result could not be verified', 1);

INSERT INTO resultTypes (code, description, enabled) VALUES
('COMPLETED', 'The proposition was completed', 1),
('NOT_COMPLETED', 'The proposition was not completed', 1),
('UNVERIFIABLE', 'The proposition result could not be verified', 1),
('CANCELLED', 'The proposition was cancelled', 1);

INSERT INTO predictionTypes (code, description, enabled) VALUES
('WILL_HAPPEN', 'Prediction that the proposition will happen', 1),
('WILL_NOT_HAPPEN', 'Prediction that the proposition will not happen', 1);
