/*
    Gathel - V5__bulk_seed_data.sql
    Database engine: SQL Server
    Database name: Gathel

    Flyway versioned migration.

    Purpose:
    - Bulk seeding script for development/testing environments.
    - Guarantees every team member gets the exact same initial dataset
      on top of the V1-V4 migrations (schema + catalogs + base seed).

    Generates (minimum):
    - 1000 players (users with role PLAYER)
    - 5000 propositions
    - 250000 events (logs) associated to propositions
    - Payment attempts + validations + transactions + predictions
      for the 5000 propositions

    Design:
    - All data is generated with set-based batched loops (no exhaustive
      literal INSERTs).
    - Referential integrity is guaranteed: every FK is resolved from
      previously inserted rows.
    - Deterministic pseudo-random generation via CHECKSUM/RAND seeded
      from row numbers, so the dataset is reproducible across environments
      (same row counts, same distribution shapes -> same statistics,
      though exact RAND() values are not guaranteed bit-identical across
      SQL Server versions; row counts and relationships ARE identical).
    - Timestamps are coherent: createdAt values move forward in time and
      dependent rows (votes, status changes, payments, transactions,
      predictions, results) are always timestamped after their parent.
    - Distribution of events, proposition statuses, payment statuses and
      prediction outcomes is varied using modulo-based buckets driven by
      the row counter, giving a realistic, non-uniform spread.

    Important note:
    - This migration is intended for local/dev seeding only. It should
      NOT be applied against production environments.
*/

SET NOCOUNT ON;

DECLARE @now DATETIME2 = SYSDATETIME();
DECLARE @checksum VARBINARY(32) = CONVERT(VARBINARY(32), HASHBYTES('SHA2_256', 'GATHEL_BULK_SEED_V5'));

/* ==========================================================
   NUMBERS HELPER TABLE
   Robust, deterministic sequence generator (1..250000) used by
   all batched loops instead of relying on sys.all_objects sizes.
   ========================================================== */
IF OBJECT_ID('tempdb..#Numbers') IS NOT NULL DROP TABLE #Numbers;

CREATE TABLE #Numbers (n INT NOT NULL PRIMARY KEY);

;WITH L0 AS (SELECT 1 AS c UNION ALL SELECT 1),                          -- 2
 L1 AS (SELECT 1 AS c FROM L0 a CROSS JOIN L0 b),                        -- 4
 L2 AS (SELECT 1 AS c FROM L1 a CROSS JOIN L1 b),                        -- 16
 L3 AS (SELECT 1 AS c FROM L2 a CROSS JOIN L2 b),                        -- 256
 L4 AS (SELECT 1 AS c FROM L3 a CROSS JOIN L3 b),                        -- 65536
 L5 AS (SELECT 1 AS c FROM L4 a CROSS JOIN L1 b)                         -- 262144
INSERT INTO #Numbers (n)
SELECT TOP (250000) ROW_NUMBER() OVER (ORDER BY (SELECT NULL))
FROM L5;

/* ==========================================================
   CONFIGURATION
   ========================================================== */
DECLARE @PLAYER_COUNT          INT = 1000;
DECLARE @PROPOSITION_COUNT     INT = 5000;
DECLARE @EVENTS_PER_PROPOSITION INT = 50;   -- 5000 * 50 = 250000 events
DECLARE @PLAYER_BATCH          INT = 200;
DECLARE @PROPOSITION_BATCH     INT = 250;
DECLARE @EVENT_BATCH_PROPOSITIONS INT = 100; -- propositions processed per event-loop batch

/* ==========================================================
   STEP 0: BASE CATALOGS AND PREREQUISITE DATA (idempotent)
   Inserts everything V5 depends on if it is not present yet
   (covers the case where V2/V3 catalog seeds were not applied).
   All inserts are guarded with IF NOT EXISTS so re-running this
   migration, or running it after V2/V3, never creates duplicates.
   ========================================================== */
PRINT 'Seeding base catalogs (idempotent)...';

/* LOG CATALOGS */
IF NOT EXISTS (SELECT 1 FROM logTypes)
INSERT INTO logTypes (code, description, enabled) VALUES
('USER', 'Events generated by users', 1),
('AI', 'Events generated by artificial intelligence processes', 1),
('SYSTEM', 'Internal system events', 1),
('SECURITY', 'Security and authorization events', 1),
('PAYMENT', 'Payment related events', 1);

IF NOT EXISTS (SELECT 1 FROM eventTypes)
INSERT INTO eventTypes (code, description, enabled) VALUES
('LOGIN', 'User login', 1),
('LOGOUT', 'User logout', 1),
('INSERT', 'Insert operation', 1),
('UPDATE', 'Update operation', 1),
('DELETE', 'Delete operation', 1),
('PAYMENT_ATTEMPT', 'Payment attempt registered', 1),
('AI_REVIEW', 'AI review executed', 1),
('TRANSACTION_CREATED', 'Wallet transaction created', 1),
('PROPOSITION_CREATED', 'Proposition created', 1),
('PREDICTION_CREATED', 'Prediction created', 1);

IF NOT EXISTS (SELECT 1 FROM severities)
INSERT INTO severities (code, level, enabled) VALUES
('INFO', '1', 1),
('WARNING', '2', 1),
('ERROR', '3', 1),
('CRITICAL', '4', 1);

IF NOT EXISTS (SELECT 1 FROM sources)
INSERT INTO sources (code, description, enabled) VALUES
('FRONTEND', 'Web or mobile frontend', 1),
('BACKEND', 'REST API backend', 1),
('DATABASE', 'SQL Server database', 1),
('AI_PROVIDER', 'Artificial intelligence provider', 1),
('PAYMENT_PROVIDER', 'External payment provider', 1),
('SOCIAL_MEDIA', 'Social media platform', 1),
('FLYWAY', 'Flyway migration process', 1);

IF NOT EXISTS (SELECT 1 FROM dataObjects)
INSERT INTO dataObjects (code, description, enabled) VALUES
('USERS', 'Users table', 1),
('PROPOSITIONS', 'Propositions table', 1),
('PREDICTIONS', 'Predictions table', 1),
('PAYMENT_ATTEMPTS', 'Payment attempts table', 1),
('TRANSACTIONS', 'Transactions table', 1),
('AI_PROCESS_LOGS', 'AI process logs table', 1),
('SOCIAL_MEDIA_POSTS', 'Social media posts table', 1),
('WALLETS', 'Wallets table', 1);

/* ROLES */
IF NOT EXISTS (SELECT 1 FROM roleTypes)
INSERT INTO roleTypes (code, description, enabled) VALUES
('ADMIN', 'Database and platform administrator', 1),
('PLAYER', 'Regular Gathel player', 1),
('BUSINESS', 'Affiliated business user', 1),
('SUPPORT', 'Support operator', 1),
('READONLY', 'Read only user for reporting', 1);

/* CURRENCIES */
IF NOT EXISTS (SELECT 1 FROM currencyTypes)
INSERT INTO currencyTypes (code, description, enabled) VALUES
('FIAT', 'Real world currency', 1),
('VIRTUAL', 'Virtual platform currency', 1);

IF NOT EXISTS (SELECT 1 FROM currencies)
INSERT INTO currencies (currencyTypeId, code, name, symbol, countryId, enabled, createdAt, updatedAt, checksum)
VALUES
((SELECT id FROM currencyTypes WHERE code = 'FIAT'), 'USD', 'US Dollar', '$', NULL, 1, @now, NULL, @checksum),
((SELECT id FROM currencyTypes WHERE code = 'FIAT'), 'CRC', 'Costa Rican Colon', '₡', NULL, 1, @now, NULL, @checksum),
((SELECT id FROM currencyTypes WHERE code = 'FIAT'), 'EUR', 'Euro', '€', NULL, 1, @now, NULL, @checksum),
((SELECT id FROM currencyTypes WHERE code = 'VIRTUAL'), 'PTS', 'Gathel Points', 'pts', NULL, 1, @now, NULL, @checksum);

/* PROPOSITION / PREDICTION / RESULT CATALOGS */
IF NOT EXISTS (SELECT 1 FROM propositionStatuses)
INSERT INTO propositionStatuses (code, description, enabled) VALUES
('PROPOSED', 'Proposition was created', 1),
('UNDER_AI_REVIEW', 'Proposition is under AI review', 1),
('VOTING', 'Proposition is available for votes', 1),
('SELECTED', 'Proposition was selected after voting', 1),
('ACCEPTED', 'Proposition was accepted by target player', 1),
('REJECTED', 'Proposition was rejected by target player', 1),
('ACTIVE', 'Proposition is active for predictions', 1),
('COMPLETED', 'Proposition was completed', 1),
('CANCELLED', 'Proposition was cancelled', 1),
('UNVERIFIABLE', 'Proposition result could not be verified', 1);

IF NOT EXISTS (SELECT 1 FROM resultTypes)
INSERT INTO resultTypes (code, description, enabled) VALUES
('COMPLETED', 'The proposition was completed', 1),
('NOT_COMPLETED', 'The proposition was not completed', 1),
('UNVERIFIABLE', 'The proposition result could not be verified', 1),
('CANCELLED', 'The proposition was cancelled', 1);

IF NOT EXISTS (SELECT 1 FROM predictionTypes)
INSERT INTO predictionTypes (code, description, enabled) VALUES
('WILL_HAPPEN', 'Prediction that the proposition will happen', 1),
('WILL_NOT_HAPPEN', 'Prediction that the proposition will not happen', 1);

/* AI CATALOGS */
IF NOT EXISTS (SELECT 1 FROM aiProviders)
INSERT INTO aiProviders (code, name, enabled) VALUES
('OPENAI', 'OpenAI', 1),
('GEMINI', 'Google Gemini', 1),
('CLAUDE', 'Anthropic Claude', 1),
('LOCAL_MODEL', 'Local Model', 1);

IF NOT EXISTS (SELECT 1 FROM aiModels)
INSERT INTO aiModels (aiProviderId, modelName, version, enabled) VALUES
((SELECT id FROM aiProviders WHERE code = 'OPENAI'), 'gpt-model-placeholder', '1', 1),
((SELECT id FROM aiProviders WHERE code = 'GEMINI'), 'gemini-model-placeholder', '1', 1),
((SELECT id FROM aiProviders WHERE code = 'CLAUDE'), 'claude-model-placeholder', '1', 1),
((SELECT id FROM aiProviders WHERE code = 'LOCAL_MODEL'), 'local-safety-model', '1', 1);

IF NOT EXISTS (SELECT 1 FROM aiProcessTypes)
INSERT INTO aiProcessTypes (code, description, enabled) VALUES
('PROPOSITION_CREATION_REVIEW', 'AI review applied when a proposition is created', 1),
('ETHICAL_REVIEW', 'AI review for ethical, legal and safety rules', 1),
('RESULT_VALIDATION', 'AI review for validating proposition result evidence', 1),
('FRAUD_REVIEW', 'AI review for detecting fraud or manipulation', 1);

IF NOT EXISTS (SELECT 1 FROM aiResults)
INSERT INTO aiResults (code, description, enabled) VALUES
('APPROVED', 'AI approved the analyzed object', 1),
('REJECTED', 'AI rejected the analyzed object', 1),
('INCONCLUSIVE', 'AI could not determine a final result', 1),
('NEEDS_MORE_EVIDENCE', 'AI requires additional evidence', 1),
('ERROR', 'AI process failed', 1);

/* PAYMENT CATALOGS */
IF NOT EXISTS (SELECT 1 FROM paymentTypes)
INSERT INTO paymentTypes (code, description, enabled) VALUES
('CARD', 'Card payment through external processor', 1),
('SINPE', 'SINPE transfer through external provider', 1),
('PAYPAL', 'PayPal payment', 1),
('BANK_TRANSFER', 'Bank transfer', 1),
('INTERNAL_BALANCE', 'Internal wallet balance movement', 1);

IF NOT EXISTS (SELECT 1 FROM paymentProviders)
INSERT INTO paymentProviders (code, name, baseUrl, enabled, createdAt, updatedAt) VALUES
('PAYPAL_API', 'PayPal API', 'https://api-m.sandbox.paypal.com', 1, @now, NULL),
('SINPE_API', 'SINPE API', 'https://sandbox.sinpe.example/api', 1, @now, NULL),
('CARD_PROCESSOR', 'Card Processor Sandbox', 'https://sandbox.cardprocessor.example/api', 1, @now, NULL),
('INTERNAL_ENGINE', 'Gathel Internal Balance Engine', NULL, 1, @now, NULL);

IF NOT EXISTS (SELECT 1 FROM operationTypes)
INSERT INTO operationTypes (code, description, enabled) VALUES
('POINTS_PURCHASE', 'Purchase virtual points', 1),
('MONEY_DEPOSIT', 'Deposit real money into wallet', 1),
('MONEY_WITHDRAWAL', 'Withdraw real money from wallet', 1),
('PREDICTION_BET', 'Bet points or money on a prediction', 1),
('REWARD_PAYMENT', 'Payment of rewards to winners', 1),
('COMMISSION_PAYMENT', 'Commission payment to platform or proposition target', 1),
('PENALTY', 'Penalty applied to a player', 1);

IF NOT EXISTS (SELECT 1 FROM paymentStatuses)
INSERT INTO paymentStatuses (code, description, enabled) VALUES
('PENDING', 'Payment attempt is pending', 1),
('APPROVED', 'Payment attempt was approved', 1),
('REJECTED', 'Payment attempt was rejected', 1),
('ERROR', 'Payment attempt ended with error', 1),
('CANCELLED', 'Payment attempt was cancelled', 1),
('INSUFFICIENT_FUNDS', 'Payment attempt failed due to insufficient funds', 1);

IF NOT EXISTS (SELECT 1 FROM paymentValidationTypes)
INSERT INTO paymentValidationTypes (code, description, enabled) VALUES
('METHOD_CHECK', 'Payment method validation', 1),
('COUNTRY_CHECK', 'Country validation', 1),
('FUNDS_CHECK', 'Funds validation', 1),
('PROVIDER_RESPONSE', 'External provider response validation', 1),
('FRAUD_CHECK', 'Fraud validation', 1);

IF NOT EXISTS (SELECT 1 FROM paymentValidationStatuses)
INSERT INTO paymentValidationStatuses (code, description, enabled) VALUES
('PENDING', 'Validation is pending', 1),
('APPROVED', 'Validation was approved', 1),
('REJECTED', 'Validation was rejected', 1),
('ERROR', 'Validation ended with error', 1);

/* TRANSACTION TYPES */
IF NOT EXISTS (SELECT 1 FROM transactionTypes)
INSERT INTO transactionTypes (code, description, createdAt, createdBy, enabled) VALUES
('BALANCE_IN', 'Balance increase', @now, NULL, 1),
('BALANCE_OUT', 'Balance decrease', @now, NULL, 1),
('BET', 'Prediction bet', @now, NULL, 1),
('REWARD', 'Reward payment', @now, NULL, 1),
('COMMISSION', 'Commission payment', @now, NULL, 1),
('PENALTY', 'Penalty transaction', @now, NULL, 1),
('REDEMPTION', 'Redeemable product redemption', @now, NULL, 1);

/* GEOGRAPHY */
IF NOT EXISTS (SELECT 1 FROM countries)
INSERT INTO countries (name, isoCode, enabled) VALUES
('Costa Rica', 'CR', 1),
('United States', 'US', 1),
('Mexico', 'MX', 1),
('Colombia', 'CO', 1),
('Spain', 'ES', 1);

IF NOT EXISTS (SELECT 1 FROM states)
INSERT INTO states (countryId, name, enabled) VALUES
((SELECT id FROM countries WHERE isoCode = 'CR'), 'San Jose', 1),
((SELECT id FROM countries WHERE isoCode = 'CR'), 'Heredia', 1),
((SELECT id FROM countries WHERE isoCode = 'US'), 'Florida', 1),
((SELECT id FROM countries WHERE isoCode = 'MX'), 'Ciudad de Mexico', 1),
((SELECT id FROM countries WHERE isoCode = 'CO'), 'Bogota D.C.', 1),
((SELECT id FROM countries WHERE isoCode = 'ES'), 'Madrid', 1);

IF NOT EXISTS (SELECT 1 FROM cities)
INSERT INTO cities (stateId, name, enabled) VALUES
((SELECT id FROM states WHERE name = 'San Jose'), 'San Jose', 1),
((SELECT id FROM states WHERE name = 'Heredia'), 'Heredia', 1),
((SELECT id FROM states WHERE name = 'Florida'), 'Miami', 1),
((SELECT id FROM states WHERE name = 'Ciudad de Mexico'), 'Mexico City', 1),
((SELECT id FROM states WHERE name = 'Bogota D.C.'), 'Bogota', 1),
((SELECT id FROM states WHERE name = 'Madrid'), 'Madrid', 1);

IF NOT EXISTS (SELECT 1 FROM addresses)
INSERT INTO addresses (cityId, addressLine1, addressLine2, postalCode, latitude, longitude, createdAt, updatedAt, checksum) VALUES
((SELECT id FROM cities WHERE name = 'San Jose'), 'Gathel Headquarters', 'Central Avenue', '10101', 9.928100, -84.090700, @now, NULL, @checksum),
((SELECT id FROM cities WHERE name = 'Heredia'), 'Player Address 1', NULL, '40101', 9.998100, -84.119800, @now, NULL, @checksum),
((SELECT id FROM cities WHERE name = 'Miami'), 'Sample US Address', NULL, '33101', 25.761700, -80.191800, @now, NULL, @checksum),
((SELECT id FROM cities WHERE name = 'Mexico City'), 'Sample MX Address', NULL, '06000', 19.432600, -99.133200, @now, NULL, @checksum),
((SELECT id FROM cities WHERE name = 'Bogota'), 'Sample CO Address', NULL, '110111', 4.711000, -74.072100, @now, NULL, @checksum),
((SELECT id FROM cities WHERE name = 'Madrid'), 'Sample ES Address', NULL, '28001', 40.416800, -3.703800, @now, NULL, @checksum);

/* Link CRC currency to Costa Rica once both exist */
IF EXISTS (SELECT 1 FROM currencies WHERE code = 'CRC' AND countryId IS NULL)
   AND EXISTS (SELECT 1 FROM countries WHERE isoCode = 'CR')
UPDATE currencies
SET countryId = (SELECT id FROM countries WHERE isoCode = 'CR')
WHERE code = 'CRC';

/* PAYMENT METHODS */
IF NOT EXISTS (SELECT 1 FROM paymentMethods)
INSERT INTO paymentMethods (paymentTypeId, paymentProviderId, countryId, name, configurationJson, enabled, createdAt, updatedAt, checksum) VALUES
((SELECT id FROM paymentTypes WHERE code = 'PAYPAL'), (SELECT id FROM paymentProviders WHERE code = 'PAYPAL_API'), NULL, 'PayPal Sandbox', '{"environment":"sandbox"}', 1, @now, NULL, @checksum),
((SELECT id FROM paymentTypes WHERE code = 'SINPE'), (SELECT id FROM paymentProviders WHERE code = 'SINPE_API'), (SELECT id FROM countries WHERE isoCode = 'CR'), 'SINPE Costa Rica Sandbox', '{"environment":"sandbox","country":"CR"}', 1, @now, NULL, @checksum),
((SELECT id FROM paymentTypes WHERE code = 'CARD'), (SELECT id FROM paymentProviders WHERE code = 'CARD_PROCESSOR'), NULL, 'External Card Processor Sandbox', '{"environment":"sandbox","storeCards":false}', 1, @now, NULL, @checksum),
((SELECT id FROM paymentTypes WHERE code = 'INTERNAL_BALANCE'), (SELECT id FROM paymentProviders WHERE code = 'INTERNAL_ENGINE'), NULL, 'Gathel Internal Balance', '{"internal":true}', 1, @now, NULL, @checksum);

/* ADMIN USER (required as createdBy for players and as actor for logs) */
IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin')
INSERT INTO users (name, lastName, username, email, password, enabled, checksum, createdAt, updatedAt, lastLogin, roleTypeId, createdBy, updatedBy, addressId)
VALUES (
    'System',
    'Admin',
    'admin',
    'admin@gathel.local',
    CONVERT(VARBINARY(256), HASHBYTES('SHA2_256', 'Admin123!')),
    1,
    @checksum,
    @now,
    NULL,
    NULL,
    (SELECT id FROM roleTypes WHERE code = 'ADMIN'),
    NULL,
    NULL,
    (SELECT MIN(id) FROM addresses)
);

/* SETTINGS (needed for app-level constants such as MAX_POINTS_PER_PREDICTION) */
IF NOT EXISTS (SELECT 1 FROM settingsTypes)
INSERT INTO settingsTypes (code, description, enabled) VALUES
('INITIAL_PLAYER_POINTS', 'Initial points assigned to a player', 1),
('REJECT_PENALTY_POINTS', 'Points penalty when selected proposition is rejected', 1),
('UNVERIFIABLE_PENALTY_PERCENTAGE', 'Penalty percentage when result cannot be verified', 1),
('PROPOSER_EARNINGS_PERCENTAGE', 'Earnings percentage assigned to proposition target', 1),
('PLATFORM_EARNINGS_PERCENTAGE', 'Earnings percentage assigned to Gathel platform', 1),
('MAX_POINTS_PER_PREDICTION', 'Maximum points allowed per prediction', 1);

IF NOT EXISTS (SELECT 1 FROM settings)
INSERT INTO settings (settingTypeId, settingValue, valueType, description, enabled, updatedBy, updatedAt) VALUES
((SELECT id FROM settingsTypes WHERE code = 'INITIAL_PLAYER_POINTS'), '100', 'INT', 'Each player starts with 100 Gathel points', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'REJECT_PENALTY_POINTS'), '1', 'INT', 'A player loses 1 point when rejecting the selected proposition', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'UNVERIFIABLE_PENALTY_PERCENTAGE'), '15', 'DECIMAL', 'A player loses 15 percent if result cannot be verified', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'PROPOSER_EARNINGS_PERCENTAGE'), '5', 'DECIMAL', 'Percentage assigned to the person executing the proposition', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'PLATFORM_EARNINGS_PERCENTAGE'), '5', 'DECIMAL', 'Percentage assigned to the platform', 1, NULL, @now),
((SELECT id FROM settingsTypes WHERE code = 'MAX_POINTS_PER_PREDICTION'), '1', 'INT', 'Maximum points allowed per prediction', 1, NULL, @now);

PRINT 'Base catalogs ready.';

/* ==========================================================
   LOOKUPS (resolved once)
   ========================================================== */
DECLARE @adminId            INT = (SELECT TOP 1 id FROM users WHERE username = 'admin');
DECLARE @playerRoleId       INT = (SELECT id FROM roleTypes WHERE code = 'PLAYER');
DECLARE @ptsId              INT = (SELECT id FROM currencies WHERE code = 'PTS');
DECLARE @usdId              INT = (SELECT id FROM currencies WHERE code = 'USD');
DECLARE @crcId              INT = (SELECT id FROM currencies WHERE code = 'CRC');

DECLARE @statusProposed     INT = (SELECT id FROM propositionStatuses WHERE code = 'PROPOSED');
DECLARE @statusUnderReview  INT = (SELECT id FROM propositionStatuses WHERE code = 'UNDER_AI_REVIEW');
DECLARE @statusVoting       INT = (SELECT id FROM propositionStatuses WHERE code = 'VOTING');
DECLARE @statusSelected     INT = (SELECT id FROM propositionStatuses WHERE code = 'SELECTED');
DECLARE @statusAccepted     INT = (SELECT id FROM propositionStatuses WHERE code = 'ACCEPTED');
DECLARE @statusRejected     INT = (SELECT id FROM propositionStatuses WHERE code = 'REJECTED');
DECLARE @statusActive       INT = (SELECT id FROM propositionStatuses WHERE code = 'ACTIVE');
DECLARE @statusCompleted    INT = (SELECT id FROM propositionStatuses WHERE code = 'COMPLETED');
DECLARE @statusCancelled    INT = (SELECT id FROM propositionStatuses WHERE code = 'CANCELLED');
DECLARE @statusUnverifiable INT = (SELECT id FROM propositionStatuses WHERE code = 'UNVERIFIABLE');

DECLARE @resultCompleted    INT = (SELECT id FROM resultTypes WHERE code = 'COMPLETED');
DECLARE @resultNotCompleted INT = (SELECT id FROM resultTypes WHERE code = 'NOT_COMPLETED');
DECLARE @resultUnverifiable INT = (SELECT id FROM resultTypes WHERE code = 'UNVERIFIABLE');
DECLARE @resultCancelled    INT = (SELECT id FROM resultTypes WHERE code = 'CANCELLED');

DECLARE @predTypeWill       INT = (SELECT id FROM predictionTypes WHERE code = 'WILL_HAPPEN');
DECLARE @predTypeWillNot    INT = (SELECT id FROM predictionTypes WHERE code = 'WILL_NOT_HAPPEN');

DECLARE @paymentMethodInternal INT = (SELECT id FROM paymentMethods WHERE name = 'Gathel Internal Balance');
DECLARE @opBet              INT = (SELECT id FROM operationTypes WHERE code = 'PREDICTION_BET');
DECLARE @opReward           INT = (SELECT id FROM operationTypes WHERE code = 'REWARD_PAYMENT');

DECLARE @payStatusApproved  INT = (SELECT id FROM paymentStatuses WHERE code = 'APPROVED');
DECLARE @payStatusPending   INT = (SELECT id FROM paymentStatuses WHERE code = 'PENDING');
DECLARE @payStatusRejected  INT = (SELECT id FROM paymentStatuses WHERE code = 'REJECTED');
DECLARE @payStatusError     INT = (SELECT id FROM paymentStatuses WHERE code = 'ERROR');
DECLARE @payStatusCancelled INT = (SELECT id FROM paymentStatuses WHERE code = 'CANCELLED');
DECLARE @payStatusInsufficientFunds INT = (SELECT id FROM paymentStatuses WHERE code = 'INSUFFICIENT_FUNDS');

DECLARE @valTypeMethod      INT = (SELECT id FROM paymentValidationTypes WHERE code = 'METHOD_CHECK');
DECLARE @valTypeFunds       INT = (SELECT id FROM paymentValidationTypes WHERE code = 'FUNDS_CHECK');
DECLARE @valTypeProvider    INT = (SELECT id FROM paymentValidationTypes WHERE code = 'PROVIDER_RESPONSE');
DECLARE @valStatusApproved  INT = (SELECT id FROM paymentValidationStatuses WHERE code = 'APPROVED');
DECLARE @valStatusRejected  INT = (SELECT id FROM paymentValidationStatuses WHERE code = 'REJECTED');

DECLARE @txTypeBet          INT = (SELECT id FROM transactionTypes WHERE code = 'BET');
DECLARE @txTypeReward       INT = (SELECT id FROM transactionTypes WHERE code = 'REWARD');

DECLARE @logTypeUser        INT = (SELECT id FROM logTypes WHERE code = 'USER');
DECLARE @logTypeAI          INT = (SELECT id FROM logTypes WHERE code = 'AI');
DECLARE @logTypeSystem      INT = (SELECT id FROM logTypes WHERE code = 'SYSTEM');
DECLARE @logTypePayment     INT = (SELECT id FROM logTypes WHERE code = 'PAYMENT');
DECLARE @logTypeSecurity    INT = (SELECT id FROM logTypes WHERE code = 'SECURITY');

DECLARE @evtLogin           INT = (SELECT id FROM eventTypes WHERE code = 'LOGIN');
DECLARE @evtLogout          INT = (SELECT id FROM eventTypes WHERE code = 'LOGOUT');
DECLARE @evtInsert          INT = (SELECT id FROM eventTypes WHERE code = 'INSERT');
DECLARE @evtUpdate          INT = (SELECT id FROM eventTypes WHERE code = 'UPDATE');
DECLARE @evtDelete          INT = (SELECT id FROM eventTypes WHERE code = 'DELETE');
DECLARE @evtPaymentAttempt  INT = (SELECT id FROM eventTypes WHERE code = 'PAYMENT_ATTEMPT');
DECLARE @evtAiReview        INT = (SELECT id FROM eventTypes WHERE code = 'AI_REVIEW');
DECLARE @evtTransaction     INT = (SELECT id FROM eventTypes WHERE code = 'TRANSACTION_CREATED');
DECLARE @evtPropositionCreated INT = (SELECT id FROM eventTypes WHERE code = 'PROPOSITION_CREATED');
DECLARE @evtPredictionCreated  INT = (SELECT id FROM eventTypes WHERE code = 'PREDICTION_CREATED');

DECLARE @sevInfo            INT = (SELECT id FROM severities WHERE code = 'INFO');
DECLARE @sevWarning         INT = (SELECT id FROM severities WHERE code = 'WARNING');
DECLARE @sevError           INT = (SELECT id FROM severities WHERE code = 'ERROR');
DECLARE @sevCritical        INT = (SELECT id FROM severities WHERE code = 'CRITICAL');

DECLARE @srcFrontend        INT = (SELECT id FROM sources WHERE code = 'FRONTEND');
DECLARE @srcBackend         INT = (SELECT id FROM sources WHERE code = 'BACKEND');
DECLARE @srcDatabase        INT = (SELECT id FROM sources WHERE code = 'DATABASE');
DECLARE @srcAiProvider      INT = (SELECT id FROM sources WHERE code = 'AI_PROVIDER');
DECLARE @srcPaymentProvider INT = (SELECT id FROM sources WHERE code = 'PAYMENT_PROVIDER');
DECLARE @srcFlyway          INT = (SELECT id FROM sources WHERE code = 'FLYWAY');

DECLARE @doUsers            INT = (SELECT id FROM dataObjects WHERE code = 'USERS');
DECLARE @doPropositions     INT = (SELECT id FROM dataObjects WHERE code = 'PROPOSITIONS');
DECLARE @doPredictions      INT = (SELECT id FROM dataObjects WHERE code = 'PREDICTIONS');
DECLARE @doPaymentAttempts  INT = (SELECT id FROM dataObjects WHERE code = 'PAYMENT_ATTEMPTS');
DECLARE @doTransactions     INT = (SELECT id FROM dataObjects WHERE code = 'TRANSACTIONS');
DECLARE @doAiProcessLogs    INT = (SELECT id FROM dataObjects WHERE code = 'AI_PROCESS_LOGS');

DECLARE @aiModelClaude      INT = (SELECT id FROM aiModels WHERE aiProviderId = (SELECT id FROM aiProviders WHERE code = 'CLAUDE'));
DECLARE @aiProcessReview    INT = (SELECT id FROM aiProcessTypes WHERE code = 'PROPOSITION_CREATION_REVIEW');
DECLARE @aiResultApproved   INT = (SELECT id FROM aiResults WHERE code = 'APPROVED');
DECLARE @aiResultRejected   INT = (SELECT id FROM aiResults WHERE code = 'REJECTED');
DECLARE @aiResultInconclusive INT = (SELECT id FROM aiResults WHERE code = 'INCONCLUSIVE');

DECLARE @minAddressId       BIGINT = (SELECT MIN(id) FROM addresses);
DECLARE @maxAddressId       BIGINT = (SELECT MAX(id) FROM addresses);
DECLARE @addressRange       INT = (SELECT COUNT(*) FROM addresses);

DECLARE @existingUserCount  INT = (SELECT COUNT(*) FROM users WHERE roleTypeId = @playerRoleId);

/* Some sample title/description fragments for realistic propositions */
DECLARE @titleVerbs TABLE (verb VARCHAR(60));
INSERT INTO @titleVerbs (verb) VALUES
('will run 5 km'), ('will post a workout video'), ('will publish a cooking reel'),
('will finish a coding challenge'), ('will read a book this week'),
('will complete a 24h fast'), ('will paint a picture'), ('will learn a new song'),
('will clean their room'), ('will go vegan for a day'), ('will do 100 push-ups'),
('will publish a travel story'), ('will record a podcast episode'),
('will meditate for 30 minutes'), ('will bike to work'),
('will publish a dance video'), ('will write a poem'), ('will fix a bug in production'),
('will attend a live event'), ('will try a new recipe');

/* ==========================================================
   STEP 1: 1000 PLAYERS (USERS)
   ========================================================== */
PRINT 'Seeding players...';

DECLARE @i INT = 1;
DECLARE @playerBatchStart INT;

WHILE @i <= @PLAYER_COUNT
BEGIN
    INSERT INTO users (name, lastName, username, email, password, enabled, checksum, createdAt, updatedAt, lastLogin, roleTypeId, createdBy, updatedBy, addressId)
    SELECT
        CONCAT('Player', n),
        CONCAT('LastName', n),
        CONCAT('player', n),
        CONCAT('player', n, '@gathel.local'),
        CONVERT(VARBINARY(256), HASHBYTES('SHA2_256', CONCAT('Player', n, '123!'))),
        1,
        @checksum,
        DATEADD(SECOND, n * 17, @now),
        NULL,
        CASE WHEN n % 5 = 0 THEN DATEADD(HOUR, -(n % 72), @now) ELSE NULL END,
        @playerRoleId,
        @adminId,
        NULL,
        @minAddressId + (n % @addressRange)
    FROM (
        SELECT @existingUserCount + num.n AS n
        FROM #Numbers num
        WHERE num.n > @i - 1
          AND num.n <= @i - 1 + @PLAYER_BATCH
          AND num.n <= @PLAYER_COUNT
    ) seq;

    SET @i += @PLAYER_BATCH;
END;

/* Wallets for newly created players: PTS, USD, CRC */
INSERT INTO wallets (userId, currencyId, balance, enabled, createdAt, updatedAt, checksum)
SELECT u.id, c.id,
       CASE WHEN c.code = 'PTS' THEN 100.00 ELSE 25.00 END,
       1, @now, NULL, @checksum
FROM users u
CROSS JOIN currencies c
WHERE c.code IN ('PTS', 'USD', 'CRC')
  AND u.roleTypeId = @playerRoleId
  AND NOT EXISTS (
        SELECT 1 FROM wallets w WHERE w.userId = u.id AND w.currencyId = c.id
  );

/* ==========================================================
   STEP 2: PLAYER ID RANGE (for FK selection)
   ========================================================== */
DECLARE @minPlayerId INT, @maxPlayerId INT, @playerCount INT;
SELECT @minPlayerId = MIN(id), @maxPlayerId = MAX(id), @playerCount = COUNT(*)
FROM users WHERE roleTypeId = @playerRoleId;

/* ==========================================================
   STEP 3: 5000 PROPOSITIONS (+ status history + votes + AI logs)
   ========================================================== */
PRINT 'Seeding propositions...';

DECLARE @existingPropCount BIGINT = (SELECT COUNT(*) FROM propositions);
DECLARE @p INT = 1;

WHILE @p <= @PROPOSITION_COUNT
BEGIN
    ;WITH gen AS (
        SELECT
            num.n AS n,
            -- pseudo-random but deterministic per row
            ABS(CHECKSUM(num.n, 'A')) AS r1,
            ABS(CHECKSUM(num.n, 'B')) AS r2,
            ABS(CHECKSUM(num.n, 'C')) AS r3,
            ABS(CHECKSUM(num.n, 'D')) AS r4
        FROM #Numbers num
        WHERE num.n > @p - 1
          AND num.n <= @p - 1 + @PROPOSITION_BATCH
          AND num.n <= @PROPOSITION_COUNT
    )
    INSERT INTO propositions (
        title, description, proposedBy, proposedTo, propositionStatusId, selectedVoteId,
        votingStartsAt, votingClosesAt, acceptedAt, rejectedAt, challengeStartsAt, challengeEndsAt,
        enabled, createdAt, updatedAt, checksum
    )
    SELECT
        CONCAT('Player ', ((g.r2 % @playerCount)), ' ', tv.verb) AS title,
        CONCAT('Auto-generated proposition #', n, ' for week-1 bulk seed validation. Source action: ', tv.verb, '.') AS description,
        @minPlayerId + (g.r1 % @playerCount) AS proposedBy,
        @minPlayerId + ((g.r1 + 1 + (g.r2 % (@playerCount - 1))) % @playerCount) AS proposedTo,
        CASE (n % 10)
            WHEN 0 THEN @statusProposed
            WHEN 1 THEN @statusUnderReview
            WHEN 2 THEN @statusVoting
            WHEN 3 THEN @statusSelected
            WHEN 4 THEN @statusAccepted
            WHEN 5 THEN @statusRejected
            WHEN 6 THEN @statusActive
            WHEN 7 THEN @statusCompleted
            WHEN 8 THEN @statusCancelled
            ELSE @statusUnverifiable
        END AS propositionStatusId,
        NULL AS selectedVoteId,
        DATEADD(MINUTE, -(n * 3), @now) AS votingStartsAt,
        DATEADD(MINUTE, -(n * 3) + 60, @now) AS votingClosesAt,
        CASE WHEN n % 10 IN (4,6,7) THEN DATEADD(MINUTE, -(n * 3) + 65, @now) ELSE NULL END AS acceptedAt,
        CASE WHEN n % 10 = 5 THEN DATEADD(MINUTE, -(n * 3) + 65, @now) ELSE NULL END AS rejectedAt,
        CASE WHEN n % 10 IN (6,7,8,9) THEN DATEADD(MINUTE, -(n * 3) + 70, @now) ELSE NULL END AS challengeStartsAt,
        CASE WHEN n % 10 IN (6,7,8,9) THEN DATEADD(DAY, 7, DATEADD(MINUTE, -(n * 3) + 70, @now)) ELSE NULL END AS challengeEndsAt,
        1,
        DATEADD(MINUTE, -(n * 3) - 5, @now) AS createdAt,
        CASE WHEN n % 10 <> 0 THEN DATEADD(MINUTE, -(n * 3) + 65, @now) ELSE NULL END AS updatedAt,
        @checksum
    FROM gen g
    CROSS APPLY (SELECT verb FROM (
        SELECT verb, ROW_NUMBER() OVER (ORDER BY verb) AS rn FROM @titleVerbs
    ) tvx WHERE tvx.rn = (g.r3 % 20) + 1) tv;

    SET @p += @PROPOSITION_BATCH;
END;

/* Resolve the proposition id range that was just inserted */
DECLARE @minPropId BIGINT, @maxPropId BIGINT;
SELECT @minPropId = MIN(id), @maxPropId = MAX(id)
FROM propositions
WHERE id > @existingPropCount;

/* Status history: one row per proposition (initial PROPOSED -> final status) */
INSERT INTO propositionStatusHistory (propositionId, oldStatusId, newStatusId, changedBy, changeReason, changedAt, checksum)
SELECT
    pr.id,
    NULL,
    @statusProposed,
    pr.proposedBy,
    'Initial status from bulk seed',
    pr.createdAt,
    @checksum
FROM propositions pr
WHERE pr.id BETWEEN @minPropId AND @maxPropId;

INSERT INTO propositionStatusHistory (propositionId, oldStatusId, newStatusId, changedBy, changeReason, changedAt, checksum)
SELECT
    pr.id,
    @statusProposed,
    pr.propositionStatusId,
    pr.proposedTo,
    'Status transition from bulk seed',
    ISNULL(pr.updatedAt, pr.createdAt),
    @checksum
FROM propositions pr
WHERE pr.id BETWEEN @minPropId AND @maxPropId
  AND pr.propositionStatusId <> @statusProposed;

/* Proposition votes: ~3 votes per proposition from random players, only for
   propositions that reached VOTING or beyond (status code not in {0,1}) */
INSERT INTO propositionVotes (userId, propositionId, votedAt, checksum)
SELECT DISTINCT
    @minPlayerId + ((ABS(CHECKSUM(pr.id, n.k, 'V')) % @playerCount)) AS userId,
    pr.id,
    DATEADD(MINUTE, -((pr.id % 1000)) + (n.k * 2), pr.votingStartsAt),
    @checksum
FROM propositions pr
CROSS JOIN (SELECT 1 AS k UNION ALL SELECT 2 UNION ALL SELECT 3) n
WHERE pr.id BETWEEN @minPropId AND @maxPropId
  AND pr.propositionStatusId NOT IN (@statusProposed, @statusUnderReview)
  AND pr.votingStartsAt IS NOT NULL;

/* Link selectedVoteId for propositions that have SELECTED or later status,
   picking the first vote registered for that proposition */
UPDATE pr
SET selectedVoteId = v.firstVoteId
FROM propositions pr
INNER JOIN (
    SELECT propositionId, MIN(id) AS firstVoteId
    FROM propositionVotes
    WHERE propositionId BETWEEN @minPropId AND @maxPropId
    GROUP BY propositionId
) v ON v.propositionId = pr.id
WHERE pr.id BETWEEN @minPropId AND @maxPropId
  AND pr.propositionStatusId IN (@statusSelected, @statusAccepted, @statusRejected, @statusActive, @statusCompleted, @statusCancelled, @statusUnverifiable);

/* AI process logs: one AI review per proposition */
INSERT INTO aiProcessLogs (
    aiModelId, aiProcessTypeId, aiResultId, userId, propositionId, socialMediaPostId,
    appliedObjectType, appliedObjectId, prompt, requestJson, responseJson, responseSummary,
    confidence, createdAt, checksum
)
SELECT
    @aiModelClaude,
    @aiProcessReview,
    CASE (pr.id % 10)
        WHEN 5 THEN @aiResultRejected
        WHEN 8 THEN @aiResultInconclusive
        ELSE @aiResultApproved
    END,
    pr.proposedBy,
    pr.id,
    NULL,
    'PROPOSITION',
    pr.id,
    'Review the proposition according to Gathel safety rules.',
    CONCAT('{"input":"', pr.title, '"}'),
    CASE (pr.id % 10)
        WHEN 5 THEN '{"result":"REJECTED","reason":"Policy violation (seed)"}'
        WHEN 8 THEN '{"result":"INCONCLUSIVE","reason":"Insufficient context (seed)"}'
        ELSE '{"result":"APPROVED","reason":"Safe proposition (seed)"}'
    END,
    CASE (pr.id % 10)
        WHEN 5 THEN 'The proposition was rejected by the seed AI review.'
        WHEN 8 THEN 'The seed AI review could not reach a conclusion.'
        ELSE 'The proposition was approved by the seed AI review.'
    END,
    CAST(0.50 + (ABS(CHECKSUM(pr.id, 'CONF')) % 50) / 100.0 AS DECIMAL(5,4)),
    DATEADD(MINUTE, -1, pr.createdAt),
    @checksum
FROM propositions pr
WHERE pr.id BETWEEN @minPropId AND @maxPropId;

/* Proposition results for completed/terminal propositions */
INSERT INTO propositionResults (propositionId, resultTypeId, aiProcessLogId, resultAt, resultDescription, checksum)
SELECT
    pr.id,
    CASE pr.propositionStatusId
        WHEN @statusCompleted THEN @resultCompleted
        WHEN @statusCancelled THEN @resultCancelled
        WHEN @statusUnverifiable THEN @resultUnverifiable
        WHEN @statusRejected THEN @resultNotCompleted
        ELSE @resultNotCompleted
    END,
    apl.id,
    ISNULL(pr.challengeEndsAt, ISNULL(pr.updatedAt, pr.createdAt)),
    'Result generated by bulk seed',
    @checksum
FROM propositions pr
INNER JOIN aiProcessLogs apl ON apl.propositionId = pr.id
WHERE pr.id BETWEEN @minPropId AND @maxPropId
  AND pr.propositionStatusId IN (@statusCompleted, @statusCancelled, @statusUnverifiable, @statusRejected);

/* ==========================================================
   STEP 4: PAYMENT ATTEMPTS + VALIDATIONS + TRANSACTIONS + PREDICTIONS
   One payment attempt (prediction bet) per proposition, made by
   a different player than proposer/target.
   ========================================================== */
PRINT 'Seeding payment attempts, transactions and predictions...';

/* 4.1: Insert one PREDICTION_BET payment attempt per proposition */
INSERT INTO paymentAttempts (
    paymentMethodId, operationTypeId, paymentStatusId, userId, currencyId, amount,
    referenceObjectType, referenceObjectId, providerReference, transactionReference,
    requestJson, responseJson, resultMessage, errorCode, createdAt, completedAt, checksum
)
SELECT
    @paymentMethodInternal,
    @opBet,
    CASE (pr.id % 12)
        WHEN 0 THEN @payStatusPending
        WHEN 1 THEN @payStatusRejected
        WHEN 2 THEN @payStatusError
        WHEN 3 THEN @payStatusCancelled
        WHEN 4 THEN @payStatusInsufficientFunds
        ELSE @payStatusApproved
    END AS paymentStatusId,
    @minPlayerId + ((ABS(CHECKSUM(pr.id, 'PAYER')) % @playerCount)) AS userId,
    @ptsId,
    CAST(1 + (ABS(CHECKSUM(pr.id, 'AMT')) % 1) AS DECIMAL(18,2)) AS amount, -- MAX_POINTS_PER_PREDICTION = 1
    'PROPOSITION',
    pr.id,
    CONCAT('seed_ref_', pr.id),
    CONCAT('tx_seed_', pr.id),
    CONCAT('{"amount":1,"currency":"PTS","propositionId":', pr.id, '}'),
    CASE (pr.id % 12)
        WHEN 0 THEN '{"status":"pending"}'
        WHEN 1 THEN '{"approved":false,"reason":"rejected by provider (seed)"}'
        WHEN 2 THEN '{"error":"provider timeout (seed)"}'
        WHEN 3 THEN '{"status":"cancelled by user (seed)"}'
        WHEN 4 THEN '{"approved":false,"reason":"insufficient funds (seed)"}'
        ELSE '{"approved":true}'
    END,
    CASE (pr.id % 12)
        WHEN 0 THEN 'Payment attempt pending processing'
        WHEN 1 THEN 'Payment attempt rejected by provider'
        WHEN 2 THEN 'Payment attempt failed with provider error'
        WHEN 3 THEN 'Payment attempt cancelled by user'
        WHEN 4 THEN 'Payment attempt failed due to insufficient funds'
        ELSE 'Approved internal points bet'
    END,
    CASE (pr.id % 12)
        WHEN 2 THEN 'ERR_PROVIDER_TIMEOUT'
        WHEN 4 THEN 'ERR_INSUFFICIENT_FUNDS'
        ELSE NULL
    END,
    DATEADD(SECOND, 30, pr.createdAt),
    CASE (pr.id % 12)
        WHEN 0 THEN NULL
        ELSE DATEADD(SECOND, 45, pr.createdAt)
    END,
    @checksum
FROM propositions pr
WHERE pr.id BETWEEN @minPropId AND @maxPropId;

/* Resolve payment attempt id range */
DECLARE @minPayId BIGINT, @maxPayId BIGINT;
SELECT @minPayId = MIN(id), @maxPayId = MAX(id)
FROM paymentAttempts
WHERE referenceObjectType = 'PROPOSITION'
  AND referenceObjectId BETWEEN @minPropId AND @maxPropId;

/* 4.2: Validations - 2 per payment attempt (METHOD_CHECK + FUNDS_CHECK or PROVIDER_RESPONSE) */
INSERT INTO paymentAttemptValidations (
    paymentAttemptId, paymentValidationTypeId, paymentValidationStatusId,
    validationOrder, validationMessage, requestJson, responseJson, externalReference, createdAt, checksum
)
SELECT
    pa.id,
    @valTypeMethod,
    @valStatusApproved,
    1,
    'Internal balance method enabled',
    NULL,
    '{"enabled":true}',
    CONCAT('val_seed_', pa.id, '_1'),
    pa.createdAt,
    @checksum
FROM paymentAttempts pa
WHERE pa.id BETWEEN @minPayId AND @maxPayId;

INSERT INTO paymentAttemptValidations (
    paymentAttemptId, paymentValidationTypeId, paymentValidationStatusId,
    validationOrder, validationMessage, requestJson, responseJson, externalReference, createdAt, checksum
)
SELECT
    pa.id,
    CASE WHEN pa.paymentStatusId = @payStatusInsufficientFunds THEN @valTypeFunds ELSE @valTypeProvider END,
    CASE WHEN pa.paymentStatusId IN (@payStatusApproved) THEN @valStatusApproved ELSE @valStatusRejected END,
    2,
    CASE WHEN pa.paymentStatusId = @payStatusInsufficientFunds THEN 'Player does not have enough points'
         WHEN pa.paymentStatusId = @payStatusApproved THEN 'Provider confirmed transaction'
         ELSE 'Provider validation failed (seed)'
    END,
    NULL,
    CASE WHEN pa.paymentStatusId = @payStatusApproved THEN '{"confirmed":true}' ELSE '{"confirmed":false}' END,
    CONCAT('val_seed_', pa.id, '_2'),
    DATEADD(SECOND, 1, pa.createdAt),
    @checksum
FROM paymentAttempts pa
WHERE pa.id BETWEEN @minPayId AND @maxPayId;

/* 4.3: Transactions - only for APPROVED payment attempts (deduct from PTS wallet) */
;WITH approvedPayments AS (
    SELECT
        pa.id AS paymentAttemptId,
        pa.userId,
        pa.amount,
        pa.referenceObjectId AS propositionId,
        pa.createdAt,
        w.id AS walletId,
        w.balance AS currentBalance,
        ROW_NUMBER() OVER (ORDER BY pa.id) AS rn
    FROM paymentAttempts pa
    INNER JOIN wallets w ON w.userId = pa.userId AND w.currencyId = @ptsId
    WHERE pa.id BETWEEN @minPayId AND @maxPayId
      AND pa.paymentStatusId = @payStatusApproved
)
UPDATE w
SET balance = w.balance - ap.amount,
    updatedAt = ap.createdAt
FROM wallets w
INNER JOIN approvedPayments ap ON ap.walletId = w.id;

INSERT INTO transactions (
    transactionTypeId, walletId, paymentAttemptId, currencyId, exchangeRateId,
    amount, balanceBefore, balanceAfter, referenceType, referenceId, externalReference,
    description, createdBy, createdAt, checksum
)
SELECT
    @txTypeBet,
    w.id,
    pa.id,
    @ptsId,
    NULL,
    -pa.amount,
    w.balance + pa.amount,
    w.balance,
    'PROPOSITION',
    pa.referenceObjectId,
    pa.transactionReference,
    'Bulk seed prediction bet using Gathel points',
    pa.userId,
    DATEADD(SECOND, 2, pa.completedAt),
    @checksum
FROM paymentAttempts pa
INNER JOIN wallets w ON w.userId = pa.userId AND w.currencyId = @ptsId
WHERE pa.id BETWEEN @minPayId AND @maxPayId
  AND pa.paymentStatusId = @payStatusApproved;

/* 4.4: Predictions - one per APPROVED payment attempt, referencing the bet transaction */
INSERT INTO predictions (
    predictionTypeId, predictedBy, propositionId, walletId, betTransactionId, rewardTransactionId,
    amount, winnerAmount, winner, enabled, createdAt, checksum
)
SELECT
    CASE WHEN pr.id % 2 = 0 THEN @predTypeWill ELSE @predTypeWillNot END,
    pa.userId,
    pa.referenceObjectId,
    t.walletId,
    t.id,
    NULL,
    pa.amount,
    NULL,
    CASE
        WHEN pr.propositionStatusId IN (@statusCompleted, @statusUnverifiable, @statusCancelled, @statusRejected) THEN
            CASE
                WHEN (pr.propositionStatusId = @statusCompleted AND pr.id % 2 = 0) THEN 1
                WHEN (pr.propositionStatusId IN (@statusUnverifiable, @statusCancelled, @statusRejected) AND pr.id % 2 = 1) THEN 1
                ELSE 0
            END
        ELSE NULL
    END,
    1,
    DATEADD(SECOND, 3, pa.completedAt),
    @checksum
FROM paymentAttempts pa
INNER JOIN transactions t ON t.paymentAttemptId = pa.id
INNER JOIN propositions pr ON pr.id = pa.referenceObjectId
WHERE pa.id BETWEEN @minPayId AND @maxPayId
  AND pa.paymentStatusId = @payStatusApproved;

/* 4.5: Reward transactions + winnerAmount for winning predictions on resolved propositions */
;WITH winners AS (
    SELECT
        pred.id AS predictionId,
        pred.walletId,
        pred.amount,
        w.balance AS currentBalance,
        pa.id AS paymentAttemptId
    FROM predictions pred
    INNER JOIN wallets w ON w.id = pred.walletId
    INNER JOIN transactions bt ON bt.id = pred.betTransactionId
    INNER JOIN paymentAttempts pa ON pa.id = bt.paymentAttemptId
    WHERE pred.winner = 1
      AND pa.id BETWEEN @minPayId AND @maxPayId
)
UPDATE w
SET balance = w.balance + win.amount * 2,
    updatedAt = @now
FROM wallets w
INNER JOIN winners win ON win.walletId = w.id;

INSERT INTO transactions (
    transactionTypeId, walletId, paymentAttemptId, currencyId, exchangeRateId,
    amount, balanceBefore, balanceAfter, referenceType, referenceId, externalReference,
    description, createdBy, createdAt, checksum
)
SELECT
    @txTypeReward,
    w.id,
    bt.paymentAttemptId,
    @ptsId,
    NULL,
    pred.amount * 2,
    w.balance - (pred.amount * 2),
    w.balance,
    'PROPOSITION',
    pred.propositionId,
    CONCAT('tx_seed_reward_', pred.id),
    'Bulk seed reward payment for winning prediction',
    pred.predictedBy,
    DATEADD(MINUTE, 10, bt.createdAt),
    @checksum
FROM predictions pred
INNER JOIN transactions bt ON bt.id = pred.betTransactionId
INNER JOIN wallets w ON w.id = pred.walletId
WHERE pred.winner = 1
  AND bt.paymentAttemptId BETWEEN @minPayId AND @maxPayId;

UPDATE pred
SET pred.rewardTransactionId = rt.id,
    pred.winnerAmount = pred.amount * 2
FROM predictions pred
INNER JOIN transactions bt ON bt.id = pred.betTransactionId
INNER JOIN transactions rt ON rt.referenceId = pred.propositionId
                            AND rt.transactionTypeId = @txTypeReward
                            AND rt.walletId = pred.walletId
WHERE pred.winner = 1
  AND bt.paymentAttemptId BETWEEN @minPayId AND @maxPayId;

/* ==========================================================
   STEP 5: 250,000 EVENTS (LOGS) ASSOCIATED TO PROPOSITIONS
   50 events per proposition (5000 * 50 = 250,000)
   Distributed across log types, event types, severities and sources.
   ========================================================== */
PRINT 'Seeding proposition events (logs)...';

DECLARE @batchProp INT = @minPropId;

WHILE @batchProp <= @maxPropId
BEGIN
    ;WITH batchProps AS (
        SELECT pr.id AS propositionId, pr.proposedBy, pr.proposedTo, pr.createdAt
        FROM propositions pr
        WHERE pr.id >= @batchProp AND pr.id < @batchProp + @EVENT_BATCH_PROPOSITIONS
          AND pr.id <= @maxPropId
    ),
    eventSeq AS (
        SELECT n AS k
        FROM #Numbers
        WHERE n <= @EVENTS_PER_PROPOSITION
    )
    INSERT INTO logs (
        logTypeId, eventTypeId, severityId, sourceId, dataObjectId, description,
        objectId1, objectId2, referenceId1, referenceId2, referenceDescription,
        userId, computer, checksum, postTime
    )
    SELECT
        CASE (bp.propositionId * 50 + es.k) % 5
            WHEN 0 THEN @logTypeUser
            WHEN 1 THEN @logTypeAI
            WHEN 2 THEN @logTypeSystem
            WHEN 3 THEN @logTypePayment
            ELSE @logTypeSecurity
        END AS logTypeId,
        CASE (bp.propositionId * 50 + es.k) % 10
            WHEN 0 THEN @evtLogin
            WHEN 1 THEN @evtLogout
            WHEN 2 THEN @evtInsert
            WHEN 3 THEN @evtUpdate
            WHEN 4 THEN @evtDelete
            WHEN 5 THEN @evtPaymentAttempt
            WHEN 6 THEN @evtAiReview
            WHEN 7 THEN @evtTransaction
            WHEN 8 THEN @evtPropositionCreated
            ELSE @evtPredictionCreated
        END AS eventTypeId,
        CASE (bp.propositionId * 50 + es.k) % 20
            WHEN 0 THEN @sevCritical
            WHEN 1 THEN @sevError
            WHEN 2 THEN @sevWarning
            WHEN 3 THEN @sevWarning
            ELSE @sevInfo
        END AS severityId,
        CASE (bp.propositionId * 50 + es.k) % 5
            WHEN 0 THEN @srcFrontend
            WHEN 1 THEN @srcBackend
            WHEN 2 THEN @srcDatabase
            WHEN 3 THEN @srcAiProvider
            ELSE @srcPaymentProvider
        END AS sourceId,
        CASE (bp.propositionId * 50 + es.k) % 6
            WHEN 0 THEN @doUsers
            WHEN 1 THEN @doPropositions
            WHEN 2 THEN @doPredictions
            WHEN 3 THEN @doPaymentAttempts
            WHEN 4 THEN @doTransactions
            ELSE @doAiProcessLogs
        END AS dataObjectId,
        CONCAT('Bulk seed event #', es.k, ' for proposition ', bp.propositionId) AS description,
        bp.propositionId AS objectId1,
        NULL AS objectId2,
        bp.propositionId AS referenceId1,
        NULL AS referenceId2,
        'Auto-generated event for proposition lifecycle (seed batch)' AS referenceDescription,
        CASE WHEN es.k % 2 = 0 THEN bp.proposedBy ELSE bp.proposedTo END AS userId,
        NULL AS computer,
        @checksum,
        DATEADD(MINUTE, es.k, bp.createdAt) AS postTime
    FROM batchProps bp
    CROSS JOIN eventSeq es;

    SET @batchProp += @EVENT_BATCH_PROPOSITIONS;
END;

/* ==========================================================
   STEP 6: SUMMARY LOG ENTRY
   ========================================================== */
INSERT INTO logs (logTypeId, eventTypeId, severityId, sourceId, dataObjectId, description, objectId1, objectId2, referenceId1, referenceId2, referenceDescription, userId, computer, checksum, postTime)
VALUES (
    @logTypeSystem,
    @evtInsert,
    @sevInfo,
    @srcFlyway,
    @doPropositions,
    CONCAT('Bulk seed V5 completed: ', @PLAYER_COUNT, ' players, ', @PROPOSITION_COUNT, ' propositions, ',
           @PROPOSITION_COUNT * @EVENTS_PER_PROPOSITION, ' events, ', @PROPOSITION_COUNT, ' payment attempts.'),
    NULL, NULL, NULL, NULL,
    'V5 bulk seed data',
    @adminId,
    NULL,
    @checksum,
    @now
);

IF OBJECT_ID('tempdb..#Numbers') IS NOT NULL DROP TABLE #Numbers;

PRINT 'V5 bulk seed completed successfully.';