flyway.url=jdbc:sqlserver://localhost:1433;databaseName=Gathel;encrypt=true;trustServerCertificate=true
flyway.user=sa
flyway.password=prueba

flyway.locations=filesystem:flyway/sql

flyway.defaultSchema=dbo
flyway.schemas=dbo

flyway.encoding=UTF-8
flyway.connectRetries=10

flyway.baselineOnMigrate=false
flyway.cleanDisabled=false

# =========================================================
# Notes:
# - Las contra de flyway es la de sql server
# - Flyway sirve como un trino, debe esperar a que la base de datos haya sido levantada.
# - el script de creacion de tablas debe estar dentro de las capretas de flyway.
# =========================================================